version: '3.8'

services:
  php:
    build: 
      args:
        user: root
        uid: 0
      context: ./php/
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    networks:
      - networkLaravelDigitalOcean

  mysql:
    container_name: mysql
    build: 
      context: ./mysql/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # MYSQL_DATABASE: 'programadorabordo'
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'root'
      # You can use whatever password you like
      # MYSQL_PASSWORD: 'qualquercoisa'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'qualquercoisa'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      # Where our data will be persisted
      - /volumes/api/mysql:/var/lib/mysql
    networks:
      - networkLaravelDigitalOcean

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/etc:/etc/nginx/conf.d
    networks:
      - networkLaravelDigitalOcean
    

networks:
  networkLaravelDigitalOcean:
    driver: bridge
      